platform :ios, '15.0'
use_frameworks!

# 메인 앱 (호스트 타겟)
target 'QuickStart' do
  pod 'SendbirdNetworkImage', :path => '../repo/sendbird-cocoapods/Sources/NetworkImage'
  pod 'SendbirdSplash', :path => '../repo/sendbird-cocoapods/Sources/Splash'  
  pod 'SendbirdMarkdownUI', :path => '../repo/sendbird-cocoapods/Sources/MarkdownUI'
  pod 'SendbirdAIAgentCore', :path => '../repo/sendbird-cocoapods/Sources/SendbirdAIAgentCore'
  pod 'SendbirdAIAgentMessenger', :path => '../repo/sendbird-cocoapods/Sources/SendbirdAIAgentMessenger'
  pod 'SendbirdUIMessageTemplate', '~> 3.30'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end