# TestPod Podfile - Remote GitHub integration test
# 🎯 This is exactly what end users will use!

source 'https://github.com/tezpark/cocoapod-test.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'TestPod' do
  use_modular_headers!

  # 🚀 Single line integration - exactly what users will use!
  pod 'SendbirdAIAgentMessenger', '~> 0.10.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      
      # Fix XCFramework permission issues
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' if target.name.include?('XCFramework')
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end
  
  # Fix framework script permissions
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.framework"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  
  # Add missing XCFramework support for SendbirdAIAgentCore
  xcframework_target = installer.pods_project.targets.find { |target| target.name == 'SendbirdAIAgentCore' }
  if xcframework_target
    # Change target type to aggregate target for XCFramework support
    xcframework_target.build_configurations.each do |config|
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '$(PODS_ROOT)/SendbirdAIAgentCore/Sources/SendbirdAIAgentCore'
    end
  end
end
